### ISSUE TITLE
Different versions on the pcb and the files

### ISSUE THREAD

**Issue by dabohda** [gilphilbert/DIY-Sim-Racing-FFB-Pedal-PCBs#1]
The PCB says version 1.2, but the files say V1.1. Maybe the file names should be updated.
![Screenshot 2024-09-25 235325](https://github.com/user-attachments/assets/7ccf98a6-6a70-40ef-975c-c89bbb41cb88)

**Comment by gilphilbert** [comment]
Good catch, thank you. I bumped the version when I added the WS2812 LED and replaced the files with the same filename! I fixed the files in the repo, thanks!
