### ISSUE TITLE
Power and control board request!

### ISSUE THREAD

**Issue by jockeponkenboy** [gilphilbert/DIY-Sim-Racing-FFB-Pedal-PCBs#3]
I really like your design, and i really would love to get 2 of each, Is there anyone here that have these awesome PCBs and willing to sell and ship them to me?

Its not possible to order less then 5 of each PCB on JLCPCB, and they doesn't have all parts in stock right now!

Or does someone know anyone that have 2 power boards and 2 control boards, please let me know!

By the way, awesome design!

**Comment by gilphilbert** [comment]
Thanks! 

The best way to buy is by grouping together with others - check out the discord server (link on the main page) and check the Offerings section. There's usually someone selling or looking to order there - you'll also find me (and the other devs) hanging out.

**Comment by jockeponkenboy** [comment]
Perfect, But i cant find the server, link corrupt?

**Comment by gilphilbert** [comment]
https://discord.gg/zTfQaxpAUz

Apologies, I'll update the repo with the new link
