### ISSUE TITLE
Link to Discord server broken?

### ISSUE THREAD

**Issue by bulls45** [gilphilbert/DIY-Sim-Racing-FFB-Pedal-PCBs#4]
Hi, trying to get on the Discord server but I end up in an "empty" space, both in the browser and the app. Anybody else having this issue?

**Comment by downSideSunny** [comment]
Same.  Would like to get on this discord as well.

**Comment by downSideSunny** [comment]
https://discord.gg/zTfQaxpAUz

**Comment by gilphilbert** [comment]
I've updated the main page to show the new Discord URL
